### PR TITLE
plotutils: add support for asymmetric errors to plotwitherror

### PR DESCRIPTION
**Pull request by kostrzewa**
In addition, fix a typo in the estimation of plot limits.

### CODE REVIEW

**Comment by kostrzewa** [comment]
Hmm, actually, before this is merged I think I will extend it some more to support multiple error bars, functionality which we need anyway.

**Comment by urbach** [comment]
okay, I could also merge now and then we pull again later...

**Comment by kostrzewa** [comment]
There's another small bug in the xlim computation which I just fixed, so let's hold off with the merge for another few hours, I should be done soon after lunch :)

**Comment by kostrzewa** [comment]
test code for new functionality with two levels of errors:

```
x <- seq(0.1,1,0.1)
y <- seq(0.2,2,0.2)
dx <- cbind(abs(rnorm(n=10,mean=0,sd=0.3)),abs(rnorm(n=10,mean=0,sd=0.4)))
dy <- cbind(abs(rnorm(n=10,mean=0,sd=0.1)),abs(rnorm(n=10,mean=0,sd=0.2)))
plotwitherror(x=x,y=y,dx=dx,dy=dy,mdy=dx,mdx=dy) #mdy=dx on purpose
```

**Comment by kostrzewa** [comment]
Hmm, sorry I guess I should calculate the positions of the error bars differently when the "quadrature" method is used... just a moment.

**Comment by kostrzewa** [comment]
Okay, so I guess this should be correct now... I hope

**Comment by kostrzewa** [comment]
Of course, when dealing with asymmetric errors the actual summation should be a bit more complicated than treating negative and positive deviations as independent... I guess one would have to construct some sort of likelihood function to account for the correct weighting, such that a strong negative error can actually reduce the uncertainty in the positive direction, no?

**Comment by urbach** [comment]
uh, never thought about this...

**Comment by kostrzewa** [comment]
For our case though I think this is fine. The asymmetric error is systematic and should therefore be completely independent fom the symmetric statistical error that we quote. Adding them in quadtrature separately seems OK to me.

**Comment by kostrzewa** [comment]
Hmm, we need to think about this a bit I think. So, let's say we have a symmetric statistical error and an asymmetric systematic error. When adding these in quadrature, the negative and positive deviations therefore have different weights from the statistical and systematic errors. This results in the fact that the position of the statistical error bar is skewed. So we go from this (statistical error only):

```
|-----x-----|
```

to this (statistical and systematic errors added in quadrature, individual bars shown at positions which indicate the relative contrbution of the given error to the variance):

```
|--|-------x---|----------------|
```

for example.... Is this correct or should it be:

```
|----|-----x-----|-------------|
```

, which shows the error bars at the positions ```dx[,1], sqrt(dx[,1]^2+sqrt(dx[,2]^2))...```

**Comment by kostrzewa** [comment]
Alright, so now when two errors are supplied for the default ```errsum.method="linear.quadrature"``` method, three error bars will be drawn. The two errors are shown in their absolute size and the total error is shown as an error bar of ```lwd=3```. The two other modes are also supported ("linear" and "quadrature")

I still think that "quadrature" is the better representation because it very directly shows the contribution to the total error, but I'm happy to relinquish my position.

**Comment by kostrzewa** [comment]
Ugh... need to add some more logic for dealing with a single point (nrow(dx)==NULL)

**Comment by kostrzewa** [comment]
Okay, so this seems to cover all bases now... this kind of thing should really be written along with unit tests...

**Comment by urbach** [comment]
hmm, so when to merge this... ;) ?

**Comment by kostrzewa** [comment]
Oh, yeah sorry I didn't reply to my last comment here. As far as I'm concerned I think I've covered all the necessities for backwards compatibility. In particular there was a problem because in some instances (dpaopp for example) we use one-dimensional arrays, which are not vectors. 

The default plotting style for multiple error bars is now "linear", although I still believe that the correct way of presenting multiple errors is "quadrature", unless they are highly correlated.

One thing that should be done is probably some documentation regarding the preparation of data to be plotted with multiple independent positive and negative error bars. I don't know when I will get around to doing this. If this routine is urgently needed I'll try to squeeze it in soonish or alternatively I will do it at a later point in time.

**Comment by urbach** [comment]
hmm, so what about this one...

**Comment by urbach** [comment]
Is this ready now?

**Comment by kostrzewa** [comment]
You can pull it in, but there is no documentation...

**Comment by kostrzewa** [comment]
Okay, I will have this ready tomorrow. Just need to fix the formatting.

**Comment by kostrzewa** [comment]
Done.

**Pull request merged**
